apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-app
        image: tian11qb/marketplace-be:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/tourism_marketplace"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002 # Asignamos el puerto 30002 para el API
  type: NodePort # Cambiado de ClusterIP a NodePort