# kubectl apply -f freddy-quispe-12-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freddy-quispe-12-deployment
  namespace: freddy-quispe-12-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freddy-quispe-12-deployment        # Debe coincidir con las etiquetas del Service
  template:
    metadata:
      labels:
        app: freddy-quispe-12-deployment      # Debe coincidir con las etiquetas del Service
    spec:
      containers:
      - name: freddy-quispe-12-container
        image: tian11qb/sebastian-webflux-nosql:1.2   # Reemplaza con tu imagen Docker Hub
        imagePullPolicy: IfNotPresent        # Evitar traer siempre la última versión si hay una actual
        envFrom:
        - secretRef:
            name: freddy-quispe-12-secret  # Esto cargará todos los valores como variables de entorno