# kubectl apply -f freddy-quispe-12-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: freddy-quispe-12-secret
  namespace: freddy-quispe-12-namespace
type: Opaque
data:
  DATABASE_NAME: ZWxjaGlubw==  # en Base64
  DATABASE_URI: bW9uZ29kYjovL3VzZXI6c2VjcmV0MTIzQGFjLXBnbGJqcmktc2hhcmQtMDAtMDAueWd5cXRlZS5tb25nb2RiLm5ldDoyNzAxNyxhYy1wZ2xianJpLXNoYXJkLTAwLTAxLnlneXF0ZWUubW9uZ29kYi5uZXQ6MjcwMTcsYWMtcGdsYmpyaS1zaGFyZC0wMC0wMi55Z3lxdGVlLm1vbmdvZGIubmV0OjI3MDE3Lz9zc2w9dHJ1ZSZyZXBsaWNhU2V0PWF0bGFzLXV4eWc2cy1zaGFyZC0wJmF1dGhTb3VyY2U9YWRtaW4mYXBwTmFtZT1DbHVzdGVyMA==   # en Base64

#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode